# Generated by Django 4.2.14 on 2024-08-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('account', '0001_initial'), ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='h',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
