# Generated by Django 4.2.14 on 2024-08-11 21:21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('account', '0001_initial'), ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
