# Generated by Django 4.2.14 on 2024-08-11 15:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at',
                 models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت رکورد')),
                ('updated_at', models.DateTimeField(auto_now=True,
                                                    verbose_name='زمان به روزرسانی')),
                ('title', models.CharField(max_length=100, verbose_name='نام مطلب')),
                ('content', models.TextField(verbose_name='محتوای مطلب')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('created_at',
                 models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت رکورد')),
                ('updated_at', models.DateTimeField(auto_now=True,
                                                    verbose_name='زمان به روزرسانی')),
                ('value',
                 models.IntegerField(
                     default=0, validators=[
                         django.core.validators.MinValueValidator(0),
                         django.core.validators.MaxValueValidator(5)
                     ], verbose_name='مقدار امتیاز')),
                ('article',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='article.article', verbose_name='مطلب')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
