# Generated by Django 4.2.14 on 2024-08-11 21:21

import uuid

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='article',
            name='ratings_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='نام مطلب'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.SmallIntegerField(
                db_index=True, default=0, validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5)
                ], verbose_name='مقدار امتیاز'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('article', 'user')},
        ),
    ]
