# Generated by Django 4.2.14 on 2024-08-11 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('article', '0002_article_average_rating_article_ratings_count_and_more'), ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='average_rating',
            field=models.FloatField(blank=True, default=0.0, verbose_name='میانگین امتیازها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ratings_count',
            field=models.PositiveIntegerField(blank=True, default=0,
                                              verbose_name='تعداد امتیازها'),
        ),
        migrations.AlterField(
            model_name='score',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ratings', to='article.article',
                                    verbose_name='مطلب'),
        ),
    ]
