# Generated by Django 4.2.14 on 2024-08-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('article', '0003_alter_article_average_rating_and_more'), ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       verbose_name='زمان ساخت رکورد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True,
                                       verbose_name='زمان به روزرسانی'),
        ),
        migrations.AlterField(
            model_name='score',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       verbose_name='زمان ساخت رکورد'),
        ),
        migrations.AlterField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True,
                                       verbose_name='زمان به روزرسانی'),
        ),
    ]
