# Generated by Django 4.2.14 on 2024-08-13 13:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('article', '0004_alter_article_created_at_alter_article_updated_at_and_more'),
                    ]

    operations = [
        migrations.CreateModel(
            name='FraudDetectionConfig',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('spike_threshold',
                 models.IntegerField(
                     default=500,
                     help_text='Max number of ratings in the time window before flagging.')),
                ('time_window_minutes',
                 models.IntegerField(default=10,
                                     help_text='Time window (in minutes) to analyze for spikes.')),
                ('min_score_deviation',
                 models.FloatField(
                     default=0.5,
                     help_text='Minimum standard deviation of scores to avoid flagging.')),
                ('suspicious_score_range',
                 models.IntegerField(
                     default=2,
                     help_text='Score range (e.g., 0-2) considered suspicious if dominant.')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='RatingFraudDetection',
            fields=[('id',
                     models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                         verbose_name='ID')),
                    ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                    ('created_at',
                     models.DateTimeField(auto_now_add=True, db_index=True,
                                          verbose_name='زمان ساخت رکورد')),
                    ('updated_at',
                     models.DateTimeField(auto_now=True, db_index=True,
                                          verbose_name='زمان به روزرسانی')),
                    ('is_suspicious', models.BooleanField(default=False)),
                    ('reason', models.TextField()),
                    ('score',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                       related_name='fraud_analysis', to='article.score')), ],
            options={
                'abstract': False,
            },
        ),
    ]
