# Generated by Django 4.2.14 on 2024-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('article', '0005_frauddetectionconfig_score_weight_and_more'), ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='score',
            name='reason_of_suspicion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RatingFraudDetection',
        ),
    ]
