# Generated by Django 4.2.14 on 2024-08-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('article', '0006_score_is_suspicious_score_reason_of_suspicion_and_more'), ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='need_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
