# Generated by Django 4.2.14 on 2024-08-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('article', '0007_article_need_manual_review'), ]

    operations = [
        migrations.RemoveField(
            model_name='frauddetectionconfig',
            name='suspicious_score_range',
        ),
        migrations.AlterField(
            model_name='frauddetectionconfig',
            name='min_score_deviation',
            field=models.FloatField(
                default=1.0, help_text='Minimum standard deviation of scores to avoid flagging.'),
        ),
        migrations.AlterField(
            model_name='frauddetectionconfig',
            name='spike_threshold',
            field=models.IntegerField(
                default=2000,
                help_text='Max number of ratings in the time window before flagging.'),
        ),
        migrations.AlterField(
            model_name='frauddetectionconfig',
            name='time_window_minutes',
            field=models.IntegerField(default=10,
                                      help_text='Time window in minutes to analyze for spikes.'),
        ),
    ]
